### ISSUE TITLE
Support for loading tensorflow model

### ISSUE THREAD

**Issue by Ramsonjehu** [MLRichter/receptive_field_analysis_toolbox#18]
Hi Team, 

Great work, It would be great if its possible to load tensorflow models as well. Hoping to see the feature soon.

Thanks and Regards,
Ramson Jehu K

**Comment by MLRichter** [comment]
Hi,
TensorFlow should actually be much easier to integrate, since TF actually  has a compote graph that you can somewhat easily access.
It will likely be the first major update after some minor fixes.

**Comment by MLRichter** [comment]
Looked a little bit into it.
As far as I see, this likely has to be split up into different encoders.
By far, the lowest hanging fruit in that regard would be support for Keras-Models.
For this reason, I opened a separate feature request here: https://github.com/MLRichter/receptive_field_analysis_toolbox/issues/22
For native tensorflow-models some other approach needs to found.

**Comment by MLRichter** [comment]
Since release https://github.com/MLRichter/receptive_field_analysis_toolbox/releases/tag/v1.2.0 this toolbox supports keras.Model-objects of Tensorflow.
