### ISSUE TITLE
`width != height` support [FR]

### ISSUE THREAD

**Issue by OverLordGoldDragon** [MLRichter/receptive_field_analysis_toolbox#19]
Thanks for your work.

It'd be helpful for `r` to take on input's dimensionality - i.e. measure receptive field of height and width separately, in case strides and kernel sizes aren't equal throughout the network. The current workaround is to move the dimension of interest to be the first - so if `(width, height) = (100, 200)`, we do `(200, 100)` and swap all network parameters.

**Comment by MLRichter** [comment]
Good point, this change permeates through various parts of the library, so there is no quick fix to change this. 
That being said, I see your point and I will come back with some estimates on how long it will take to implement.

**Comment by MLRichter** [comment]
Hi,
I managed to build a little prototype, there also will be a new color.
Yellow, which is in cases where the receptive field is on some axis bigger than the input resolution bot not all axes.
This happens for example in InceptionV3, which makes some use of non-square receptive field sizes.
[inceptionv3_32_pixels.pdf](https://github.com/MLRichter/receptive_field_analysis_toolbox/files/7855481/inceptionv3_32_pixels.pdf)

Release will be very soon.

**Comment by MLRichter** [comment]
This issue has been addressed with PR: https://github.com/MLRichter/receptive_field_analysis_toolbox/pull/21
Feature is implemented
