### ISSUE TITLE
Is GraphViz an essential program of rfa_toolbox?

### ISSUE THREAD

**Issue by songyuc** [MLRichter/receptive_field_analysis_toolbox#20]
**Describe the bug**
I met this error as,
> Traceback (most recent call last):
...
File "...\lib\site-packages\graphviz\_tools.py", line 172, in wrapper
  return func(*args, **kwargs)
File "...\lib\site-packages\graphviz\backend\[rendering.py](http://rendering.py)", line 317, in render
  execute.run_check(cmd,
File "...\lib\site-packages\graphviz\backend\[execute.py](http://execute.py)", line 88, in run_check
  raise ExecutableNotFound(cmd) from e
graphviz.backend.execute.ExecutableNotFound: failed to execute WindowsPath('dot'), make sure the Graphviz executables are on your systems' PATH

**To Reproduce**

**Additional context**
I am wondering whether GraphViz is an essential program of rfa_toolbox.

Your answer and guide will be appreciated!

**Comment by MLRichter** [comment]
Hello!
Yes, GraphViz is a dependency necessary for rendering and viewing graphs.
The Problem is that only the python "frontend" can be installed via pip, while the program GraphViz needs to be installed additionally, since pip cannot resolve non-python dependencies.

Here is a guide for the GraphViz-installation in Windows:
https://forum.graphviz.org/t/new-simplified-installation-procedure-on-windows/224

**Comment by songyuc** [comment]
你好，您的邮件我已经收到，谢谢您！~O(∩_∩)O~                                                    宋玉成

**Comment by songyuc** [comment]
After I installed GraphViz, I run the [sample](https://github.com/MLRichter/receptive_field_analysis_toolbox#pytorch) again.
And it prompts as,
> ...\lib\site-packages\torch\nn\functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
...\lib\site-packages\torch\jit\_trace.py:977: TracerWarning: Output nr 1. of the traced function does not match the corresponding output of the Python function. Detailed error:
With rtol=1e-05 and atol=1e-05, found 996 element(s) (out of 1000) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 0.029880713671445847 (0.004493381828069687 vs. 0.03437409549951553), which occurred at index (0, 449).
  _check_trace(
> 
> Process finished with exit code 0

Besides, there seems no graphic results.

**Comment by MLRichter** [comment]
The warning seem normal to regarding the JIT-compiler output.
The` render()` will save the graph to your local folder as PDF. If you want a pop-up window use `view()` instead.

That being said, I see that this is probably a bit confusing. I will change the code in the example accordingly.

**Comment by songyuc** [comment]
Thanks very much for your answers.
Though this work is substantial, I might be able to follow it, as I have a different understanding concept of the Reception Field.
