### ISSUE TITLE
required keyword attribute 'name' is undefined

### ISSUE THREAD

**Issue by OverLordGoldDragon** [MLRichter/receptive_field_analysis_toolbox#33]
[This layer](https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/layers/drop.py#L104) uses a custom function in `forward` and yields

```python
    graph = create_graph_from_pytorch_model(m, input_res=in_shape)

  File "D:\Anaconda\envs\pyt\lib\site-packages\rfa_toolbox\encodings\pytorch\ingest_architecture.py", line 291, in create_graph_from_model
    return make_graph(tm, ref_mod=model).to_graph()

  File "D:\Anaconda\envs\pyt\lib\site-packages\rfa_toolbox\encodings\pytorch\ingest_architecture.py", line 172, in make_graph
    make_graph(

  File "D:\Anaconda\envs\pyt\lib\site-packages\rfa_toolbox\encodings\pytorch\ingest_architecture.py", line 172, in make_graph
    make_graph(

  File "D:\Anaconda\envs\pyt\lib\site-packages\rfa_toolbox\encodings\pytorch\ingest_architecture.py", line 172, in make_graph
    make_graph(

  File "D:\Anaconda\envs\pyt\lib\site-packages\rfa_toolbox\encodings\pytorch\ingest_architecture.py", line 132, in make_graph
    submodule_name = find_name(list(n.inputs())[0], self_input)

  File "D:\Anaconda\envs\pyt\lib\site-packages\rfa_toolbox\encodings\pytorch\ingest_architecture.py", line 34, in find_name
    cur = i.node().s("name")

RuntimeError: required keyword attribute 'name' is undefined
```

Perhaps default to a generic name if it can't be extracted

**Comment by MLRichter** [comment]
This PR should address this: https://github.com/MLRichter/receptive_field_analysis_toolbox/pull/34

Can you check whether this fixes it for you, or provide a minimal code example, so I can test it myself?

**Comment by MLRichter** [comment]
The PR has been updated.
The following code works now more or less propery 

`if __name__ == '__main__':
    model = torch.nn.Sequential(
        torch.nn.Conv2d(3, 64, kernel_size=3, stride=1, padding=1),
        torch.nn.ReLU(),
        DropBlock2d(0.1, 7, gamma_scale=1.0, with_noise=True, inplace=True, batchwise=True),
        torch.nn.Conv2d(64, 64, kernel_size=3, stride=1, padding=1),
        torch.nn.ReLU(),
    )
    x = torch.randn(1, 3, 224, 224)
    y = model(x)
    from rfa_toolbox import create_graph_from_pytorch_model, visualize_architecture
    import rfa_toolbox.encodings.pytorch.intermediate_graph
    rfa_toolbox.encodings.pytorch.intermediate_graph.RESOLVING_STRATEGY[-2].coerce = True
    rfa_toolbox.encodings.pytorch.intermediate_graph.RESOLVING_STRATEGY[-2].default_kernel_size = 1
    rfa_toolbox.encodings.pytorch.intermediate_graph.RESOLVING_STRATEGY[-2].default_stride_size = 1

    graph = create_graph_from_pytorch_model(model)
    visualize_architecture(graph, "DUMMY", input_res=32).view()`

**Comment by MLRichter** [comment]
The updated are included in the most recent release.
@OverLordGoldDragon  can you, please check the latest version out and see if it works?

**Comment by OverLordGoldDragon** [comment]
Errors are bypassed with `toggle_coerce_torch_functional(True)`, but the network's mapped out pretty wrong. Maybe simply ignore the effect of such layers on receptive field size, i.e. pretend it's a `pass`, and throw a warning? My workaround is to simply exclude those layers when using RFA. Also I'm using torch 1.10.0, on Windows 10.

**Comment by MLRichter** [comment]
This is basically how it is currently implemented, there is a Handler, which is supposed to catch torch.nn.functional calls of kernel-based function. If it catches it, it throws out an error. If the coerce-toggle is enabled it throws a warning instead and inject basically a pass-layer.
The true problem however lies somewhere in the JIT-compiles compute-graph from which the structure of the forward pass is basically reverse engineered.
This seems to work fine for nn.Module-type layers but as soon as a kernel-based function like average or max-pooling is used, the computed graph gets mapped out wrongly.
I have yet to come to the bottom of this.
Can you share a screenshot of the plot so I can investigate further?

**Comment by MLRichter** [comment]
Here are some fixing coming up right now that address this issue.

If you explicitly do not want a class to be visited (like drop path in your example) you can not actively disable it (see example code below):

```
if __name__ == '__main__':
    # This is the first problem I encountered with torchscript.
    # In eval model, the graph is mapped out wrong
    # During Training Time the custom drop-path module is a weird subgraph for unknown reasons.
    from involution import Involution2d
    m = torch.nn.Sequential(
        torch.nn.Conv2d(3, 64, kernel_size=3, stride=1, padding=1),
        torch.nn.ReLU(),
        Involution2d(64, 64, kernel_size=3, stride=1, padding=1),
        DropBlock2d(0.1, 7, gamma_scale=1.0, with_noise=True, inplace=True, batchwise=True),
        torch.nn.Conv2d(64, 64, kernel_size=3, stride=1, padding=1),
        torch.nn.ReLU(),
    )

    from rfa_toolbox import create_graph_from_pytorch_model
    from rfa_toolbox import visualize_architecture
    # in eval mode the graph is mapped out wrongly

    visualize_architecture(create_graph_from_pytorch_model(m, custom_layers=["DropBlock2d", "Involution2d"]), "model").view()
```

This should address the issue.
Please note that this will assume that the not-visited module will have no effect on the receptive field size.
If you do not want this, you need to write a custom Layer-Handler.
I may add some simple factory that allows you to easily create your own handlers to circumvent this.

**Comment by MLRichter** [comment]
The latest release (https://github.com/MLRichter/receptive_field_analysis_toolbox/releases/tag/v1.4.0) has addressed the issue of pooling layers.
You may also now provide a list of your own modules that you do not want the system to visit.

Not excluded (previous behavior):

```

    # Create some model
    m = torch.nn.Sequential(
        torch.nn.Conv2d(3, 64, kernel_size=3, stride=1, padding=1),
        torch.nn.ReLU(),
        Involution2d(64, 64, kernel_size=3, stride=1, padding=1),
        DropBlock2d(0.1, 7, gamma_scale=1.0, with_noise=True, inplace=True, batchwise=True),
        torch.nn.Conv2d(64, 64, kernel_size=3, stride=1, padding=1),
        torch.nn.ReLU(),
    )

    from rfa_toolbox import create_graph_from_pytorch_model
    from rfa_toolbox import visualize_architecture
    visualize_architecture(
        create_graph_from_pytorch_model(m),
        "model"
    ).view()
```

![excluded](https://user-images.githubusercontent.com/20163458/151527907-5370c520-6652-4e50-b4ac-e807bd31c9e2.PNG)

With excluded modules:

```
    # Create some model
    m = torch.nn.Sequential(
        torch.nn.Conv2d(3, 64, kernel_size=3, stride=1, padding=1),
        torch.nn.ReLU(),
        Involution2d(64, 64, kernel_size=3, stride=1, padding=1),
        DropBlock2d(0.1, 7, gamma_scale=1.0, with_noise=True, inplace=True, batchwise=True),
        torch.nn.Conv2d(64, 64, kernel_size=3, stride=1, padding=1),
        torch.nn.ReLU(),
    )

    from rfa_toolbox import create_graph_from_pytorch_model
    from rfa_toolbox import visualize_architecture
    visualize_architecture(
        create_graph_from_pytorch_model(m, custom_layers=["DropBlock2d", "Involution2d"]),
        "model"
    ).view()
```

results in:
![excluded](https://user-images.githubusercontent.com/20163458/151528210-bb3d23af-1642-4aa7-9517-75fdccd10f4d.PNG)

Does this solve your problem?

**Comment by OverLordGoldDragon** [comment]
Doesn't seem to work

<details><summary>error</summary>

```python
Traceback (most recent call last):

  File "D:\Anaconda\envs\pyt\lib\site-packages\rfa_toolbox\encodings\pytorch\ingest_architecture.py", line 115, in find_name
    cur = i.node().s("name")

RuntimeError: required keyword attribute 'name' is undefined


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Desktop\School\Deep Learning\DL_Code\SeizureClassification\untitled0.py", line 38, in <module>
    graph = create_graph_from_pytorch_model(m, input_res=in_shape,

  File "D:\Anaconda\envs\pyt\lib\site-packages\rfa_toolbox\encodings\pytorch\ingest_architecture.py", line 394, in create_graph_from_model
    return make_graph(tm, ref_mod=model, classes_to_not_visit=custom_layers).to_graph()

  File "D:\Anaconda\envs\pyt\lib\site-packages\rfa_toolbox\encodings\pytorch\ingest_architecture.py", line 248, in make_graph
    make_graph(

  File "D:\Anaconda\envs\pyt\lib\site-packages\rfa_toolbox\encodings\pytorch\ingest_architecture.py", line 248, in make_graph
    make_graph(

  File "D:\Anaconda\envs\pyt\lib\site-packages\rfa_toolbox\encodings\pytorch\ingest_architecture.py", line 216, in make_graph
    submodule_name = find_name(list(n.inputs())[0], self_input)

  File "D:\Anaconda\envs\pyt\lib\site-packages\rfa_toolbox\encodings\pytorch\ingest_architecture.py", line 117, in find_name
    return suffix + "-unknownType"

TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```
</details>

I've mailed the library and code to reproduce the error.

**Comment by MLRichter** [comment]
Fixed it, the next release will contain the fix.
[model.pdf](https://github.com/MLRichter/receptive_field_analysis_toolbox/files/7960203/model.pdf)
Please retry for yourself as soon as version 1.4.1 is deployed (in about 30 Minutes or so).

**Comment by OverLordGoldDragon** [comment]
Works, thanks!

Might be worth pursuing a default behavior of automatically catching such layers and throwing warnings to ease burden on user. Feel free to close.

**Comment by MLRichter** [comment]
The problem here is that a proper discriminator is needed to check that it's not just another module like BasicBlock of ResNet or something similar. I have yet to come up with something that is not annoying (aka burping out a warning every single time) versus something that never-ever triggers. However, I strongly agree with you and I will keep being on the lookout!
Thanks for your feedback!
