### ISSUE TITLE
Question: does the tool support Jypyter Lab/Notebook?

### ISSUE THREAD

**Issue by Michelvl92** [MLRichter/receptive_field_analysis_toolbox#43]
I am working on a remote machine with only terminal access. When running the tool with Jupiter notebook I am getting the following error:

```
Error: no "view" mailcap rules found for type "application/pdf"
/usr/bin/xdg-open: line 869: www-browser: command not found
/usr/bin/xdg-open: line 869: links2: command not found
/usr/bin/xdg-open: line 869: elinks: command not found
/usr/bin/xdg-open: line 869: links: command not found
/usr/bin/xdg-open: line 869: lynx: command not found
/usr/bin/xdg-open: line 869: w3m: command not found
xdg-open: no method available for opening '.gv.pdf'
```

Is it possible to open the graph through jupyter? Or is this currently not supported?

**Comment by MLRichter** [comment]
Disclaimer: I never tried it before.
But the graphs entirely based on GraphViz; therefore some support is baked in: https://h1ros.github.io/posts/introduction-to-graphviz-in-jupyter-notebook/

That being said, I am currently speaking with potential contributors to create more dedicated support for notebooks.
This involves stuff like javascript-callbacks that would allow you to make a graphviz-vizualization interactive and adjust the scope of the nodes etc. but It's still very much an idea, so do not expect it anytime soon.
